env:
    pythonunbuffered: ENC[AES256_GCM,data:Tg==,iv:0QvGUUsbtMmuKldOlnLq4ULrCX9X1La5aKSh4XchJyY=,tag:Z6i7Ul+H1vgagmtv3zR/5g==,type:str]
    databaseUrl: ENC[AES256_GCM,data:pr+37dWQ3I96vF2x52/tRXFf0RueGI5sdfP1+Qtv1vnOjFH1NDjmxrI4mgvP7M0U2r8=,iv:26Arnte43Mfk7p4WZZCyVGW1Ku2J6VfQe6uPnOAS2i8=,tag:+X74RdnCqAROj+DMRzcd+w==,type:str]
    databaseHost: ENC[AES256_GCM,data:Nz5nW57WpV6jNioz5/0KUtRJLWaG7LSEMeOAd4jDY8MS+xgYPnyHpEWIIprCKJ+o6O8=,iv:2y3/jsJtfJgEm44PpePP9GAWogewMAihYexFJfO15Pc=,tag:MaxmBOiFzxAjAO5Lg3xMjQ==,type:str]
    databasePort: ENC[AES256_GCM,data:PXpl9A==,iv:LM7lmUteTDOMRPgTg7dWoId0+Usjfnsa3gbwOejPUZQ=,tag:Bu9pq89DbWVTBfQJJf/VXw==,type:str]
    databaseUser: ENC[AES256_GCM,data:Z2vbjMmSN76pYWbE1NZPF+I=,iv:1h/juRyZzHU9C1lS5aLjzEVAxzCv0pUQfCfkcWa1MFk=,tag:ZjBx4yp8jPjP8oWUECmeoQ==,type:str]
    databasePassword: ENC[AES256_GCM,data:l7yyIJBFtNlh2GaKi6uo1MfOjGhV01uMebQnzZfulFI=,iv:MbJSf+l/kHX66GTbo19uyuvofRLlGqLdAiNnR+p4ElE=,tag:LckRJHR2ySWX19UEZos6ZA==,type:str]
    databaseName: ENC[AES256_GCM,data:RYtgcL3WXOiEzVIk,iv:G+oQ2BIFBkQFgjOAaSkDwZBqzaJlEMM9rrSoxDejanY=,tag:nrXQv5uaHYK/XpDX9L8H0g==,type:str]
    adminEmail: ENC[AES256_GCM,data:mojWKamrr0NMp+ZKNsd0YdsOtO8TYULFKw==,iv:8BtU8Zwkav4OBDot+EfRy2SZld/qDaVHDWp8Tt3KJAA=,tag:6MTu9uIatA2c0bqD2CPpmQ==,type:str]
    adminPassword: ENC[AES256_GCM,data:MG0VdN/csEdNBcfRWow=,iv:R8RunKcaRsWX6Ixb3P8o4wioaXy5Byy+oKmeU2vbhUw=,tag:r3jPVlumc3LayYD8VXiG8w==,type:str]
    adminUsername: ENC[AES256_GCM,data:01kO8VM=,iv:7eMI3CEWTLHZHYNSpTshJbGjKrEkJd6yJQqvMCPoyRU=,tag:7mQOVf3J+gOazrex7+Qwjw==,type:str]
    jwtSecretKey: ENC[AES256_GCM,data:nx5t56060XIbK9u45YO9JUnkS3VEATMq7mY07uo=,iv:etRfTz96btJsH7+qYFPvn4ZEOHvvJSak43zybKO/lqA=,tag:doY56Y1BIFqV2tKq7WXuBg==,type:str]
    engineUrl: ENC[AES256_GCM,data:zxiKXpdHrD+dw3N7Y1yOvWEHVlWfxASvp1eSxZlO6Q==,iv:0V+FkYyjKbfOKDFG+05qZLHqic+COm6wbtHnIjokaAk=,tag:RUawTztRSAtkABl2/q5v1Q==,type:str]
    internalAuthToken: ENC[AES256_GCM,data:D4ZicBreZSuC03jEhSzn3rzo4mU8,iv:jIK3zQ8U7EVMhot4H01cVrWxeA/S9sI351pwrjEu1fo=,tag:6TXdL1rgpKpwWVdfsYRy0Q==,type:str]
    ollamaUrl: ENC[AES256_GCM,data:E2T1RLP5ZOiFbM6pBUt8rIT+hWMmg4ti,iv:Ab3oDHwjpE8eddhqb/gt+EETvFODDskwSFOsKK3EZk4=,tag:iVjU4VTms2EVsgoWU/RgTg==,type:str]
    ollamaModel: ENC[AES256_GCM,data:MjOHYdgVRrs=,iv:+9n7C3MbfNDQ8NMtj7BRk+KYc4PapzGhM2Rs7APxj6w=,tag:iHpaV/jS8Zo8DsrFrjz+1w==,type:str]
sops:
    age:
        - recipient: age1x3l5pk8f4rsez6gcs7m7ledppcx4s76w3kenqkc45kqeqmj4dphsz63afe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIcmM5VWZKWnR4SWsrODRi
            RjN6ZElBMmtScm1tSkpvMUpHNGplU2UvbmlVCnNRSlUybkdsdFArNEFXYnMwV1Nn
            YUYrajV5Sm1CS0JCZFNPSXRld3FQbGMKLS0tIGdRV3lISzEyNWhiUmNkaHpZWnpa
            U0F4MWxRSGRqWUxNWUFQZGtWeVEvQVEKKkoHqIQ2Ap741yQzpiHdowVgobgYeqds
            yLkwcEMVH9zvB65sdmxnAsnmWwx3xhuBK7xnB8/a87KnGMDinkn6mQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-14T18:17:49Z"
    mac: ENC[AES256_GCM,data:kdwtdnUPtwE7YNv2/GMRGUMqiVnXR67eiG5leJsBn6e2thSkN/CGuEejCcI27ND3WUgBrEQk5TWaWTPB+Kvr+HFCDE31fuC1/lPbnChLtwyPTkZk3r+mjzG93DCEmy1lLptmBWMvrSRekChf2ieeL+y/XGXuxLLa+Wxwmlq5nmc=,iv:XHsUMKinapcS/yoEJ4F3pn94KZTMF/3BpPB6Y61LRYY=,tag:nrGmiCXpVHo0wCjZCzHfCQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
