service:
  port: 80
resources:
  requests:
    cpu: 10m
    memory: 100Mi
env:
  viteBackendUrl: "http://backend.stipendiatet.svc.cluster.local:8000/api"
ingress:
  host: stipendieadmin.labb.site
image:
  repository: ghcr.io/seppaleinen/stipendariet/admin
  tag: latest
