"""Add multi-profile support

Revision ID: b64ec2432846
Revises: f7e3b1865c07
Create Date: 2026-02-03 10:33:05.823386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = 'b64ec2432846'
down_revision: Union[str, Sequence[str], None] = 'f7e3b1865c07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Helper to check if a column exists
    bind = op.get_bind()
    insp = sa.inspect(bind)
    
    def column_exists(table, column):
        columns = insp.get_columns(table)
        return any(c["name"] == column for c in columns)

    def index_exists(table, index):
        indexes = insp.get_indexes(table)
        return any(i["name"] == index for i in indexes)

    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop scholarships if it exists
    tables = insp.get_table_names()
    if 'scholarships' in tables:
        if index_exists('scholarships', 'ix_scholarships_embedding_ivfflat'):
            op.drop_index('ix_scholarships_embedding_ivfflat', table_name='scholarships', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
        op.drop_table('scholarships')

    # Drop foundations indexes
    foundation_indexes = [
        'ix_foundations_category', 'ix_foundations_county_code', 
        'ix_foundations_enrichment_status', 'ix_foundations_municipality_code', 
        'ix_foundations_name'
    ]
    for idx in foundation_indexes:
        if index_exists('foundations', idx):
            op.drop_index(idx, table_name='foundations')

    # Add columns to profiles
    if not column_exists('profiles', 'name'):
        op.add_column('profiles', sa.Column('name', sa.String(), nullable=True))
    if not column_exists('profiles', 'is_default'):
        op.add_column('profiles', sa.Column('is_default', sa.Boolean(), nullable=True))
    
    # Data migration for existing profiles
    op.execute("UPDATE profiles SET name = 'Min profil' WHERE name IS NULL")
    op.execute("UPDATE profiles SET is_default = true WHERE is_default IS NULL")
    
    # Now make name nullable=False (only if it is still nullable)
    name_col = next((c for c in insp.get_columns('profiles') if c['name'] == 'name'), None)
    if name_col and name_col.get('nullable', True):
        op.alter_column('profiles', 'name', nullable=False)

    # Drop profiles indexes
    if index_exists('profiles', 'ix_profiles_county_code'):
        op.drop_index('ix_profiles_county_code', table_name='profiles')
    if index_exists('profiles', 'ix_profiles_municipality_code'):
        op.drop_index('ix_profiles_municipality_code', table_name='profiles')
    
    # Drop constraint — use SAVEPOINT so a missing constraint doesn't abort the transaction
    op.execute("SAVEPOINT sp_drop_profiles_unique")
    try:
        op.drop_constraint('profiles_user_id_key', 'profiles', type_='unique')
        op.execute("RELEASE SAVEPOINT sp_drop_profiles_unique")
    except Exception:
        op.execute("ROLLBACK TO SAVEPOINT sp_drop_profiles_unique")

    # Drop old columns from profiles
    old_cols = [
        'additional_notes', 'contact_information', 'living_situation', 
        'background', 'personal_description'
    ]
    for col in old_cols:
        if column_exists('profiles', col):
            op.drop_column('profiles', col)

    users_cols = {c['name']: c for c in insp.get_columns('users')}
    if users_cols.get('hashed_password', {}).get('nullable') is False:
        op.alter_column('users', 'hashed_password',
                   existing_type=sa.VARCHAR(),
                   nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(),
               existing_nullable=True)

    op.execute("CREATE UNIQUE INDEX IF NOT EXISTS ix_users_google_id ON users (google_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_users_id ON users (id)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('profiles', sa.Column('personal_description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('background', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('living_situation', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('contact_information', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('additional_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('profiles_user_id_key'), 'profiles', ['user_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_profiles_municipality_code'), 'profiles', ['municipality_code'], unique=False)
    op.create_index(op.f('ix_profiles_county_code'), 'profiles', ['county_code'], unique=False)
    op.drop_column('profiles', 'is_default')
    op.drop_column('profiles', 'name')
    op.create_index(op.f('ix_foundations_name'), 'foundations', ['name'], unique=False)
    op.create_index(op.f('ix_foundations_municipality_code'), 'foundations', ['municipality_code'], unique=False)
    op.create_index(op.f('ix_foundations_enrichment_status'), 'foundations', ['enrichment_status'], unique=False)
    op.create_index(op.f('ix_foundations_county_code'), 'foundations', ['county_code'], unique=False)
    op.create_index(op.f('ix_foundations_category'), 'foundations', ['category'], unique=False)
    op.create_table('scholarships',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('organization_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('organization_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('requirements', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('deadline', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('application_method', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('official_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('NEW', 'NEEDS_REVIEW', 'PUBLISHED', 'FAILED', name='scholarshipstatus'), autoincrement=False, nullable=False),
    sa.Column('scraping_method', postgresql.ENUM('MANUAL', 'AUTOMATED', name='scrapingmethod'), autoincrement=False, nullable=True),
    sa.Column('raw_scraped_content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=3), autoincrement=False, nullable=True),
    sa.Column('published', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('scholarships_pkey'))
    )
    op.create_index(op.f('ix_scholarships_embedding_ivfflat'), 'scholarships', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    # ### end Alembic commands ###
