viteSentryApi: ENC[AES256_GCM,data:R8/pkvh3v6VVcQF+YPASqoF9wut9wGreK1OzLpfabP+u75qULhnnswnnn1/oqSDuEv9Y2zG4WedFvCtEJGkrTSka9VMHk8Jo,iv:esqogykfRYDUWcnivSHgh7IGhvNZEzzI6gcYngC0s2s=,tag:4zM6HCG/NL2eRvO4+0/m+w==,type:str]
sops:
    age:
        - recipient: age1x3l5pk8f4rsez6gcs7m7ledppcx4s76w3kenqkc45kqeqmj4dphsz63afe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5L0tIOTh0azJSdWl4aU1n
            cVhlUE1RelVvSmdXYXlyYTJRM2l6aUFYRXk0CkFWcGYyQUJ1eFVPdllNZENBeXRt
            QnVuMkV5TkpzODFaQnBDcXNLVzRKWjgKLS0tIDBmRnQvbzVZU1lTTkxhckNsNnFz
            WnJwZHBSR29oRHFlb1I5WDA1UnRFNEUKzxAp39X70N4uwxhlC/E1yFVdxpeg0Awb
            Hm8HZqkiGqbb9D57DcV6rzIy2BGpCQagzjZdZUnkKJ+D0wg0KHN5lg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-01T09:15:50Z"
    mac: ENC[AES256_GCM,data:v+OB1SMfopJdAO2Py49bw6F5+/HpG6gCSYSIfHdZFdJEBjFhRfFNGBm8lkSjuJX+GKl7W9iOEzLtAy21t6aCaAC4FraANO1PHxTwsgiIWjc3Fyv4Wvw+kLtkrTzc/05H3NGo6Fg9G5F2rgfbyG5llBFEtbD88Sr2icnEUP9d0bw=,iv:+9WdZP/y3O8nLBRylSewQRphPgEbUFdqj13EfSIMxnk=,tag:LgmjdgkMmqotQ0hbAXp4Aw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
