service:
  port: 8080
resources:
  requests:
    cpu: 10m
    memory: 100Mi
ingress:
  host: stipendieassistenten.labb.site
image:
  repository: ghcr.io/seppaleinen/stipendariet/frontend
  tag: latest
env:
  viteApiUrl: "/api"
