postgres:
    password: ENC[AES256_GCM,data:XsJlelywIeDj6GmzSFd/lRcLLiFEs+QpNvaur5HYhB0=,iv:IOgXZFFDzEPdW+b1E+RaMfr3YAZkqxv9Tpy6IZJWZPg=,tag:q3B2iLgkcrhxNQgD+P7MJA==,type:str]
sops:
    age:
        - recipient: age1x3l5pk8f4rsez6gcs7m7ledppcx4s76w3kenqkc45kqeqmj4dphsz63afe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMQTkrbUk5Ui9IYUVqVE1J
            ekowN1duKzVSS1dINXZ5ci9hc2E2NUNPUlJNClRTN2lBSUwwTVVzdGQ3SUlwTWVW
            c1RvYTFUR0ZBRVNWYnVXUmk3MTljYzQKLS0tIDZQKyszRm1JQlNQOW9kZlF2NldY
            N1B5bmd2NjJjZ2pWUG14K2pXSnlXRVkKFJe0JBgKl9SNIO4byqt/pivBn4mbDsBB
            s8QebV+VnulYnX2v/izR5z/6ZKBMAin4e8dXIL2H6Aa8uFyeM1rAxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-11T20:56:30Z"
    mac: ENC[AES256_GCM,data:OqXWkUemZBZmSAerYTs8WKdC+XrL6wMdwg9fIb/fA09xoD9kJsPKxEXSao1BbBstEt3uKw0wWyfdIvOhPpXR0LLykdHBi55+BAfdwiL2i+/4Pba0AxHvJVIZkN6WRXeUQ0mqk4vDUJJ8suxiVX9I3+AEmorNQVBGGvHT6dWGm/w=,iv:DVdMk8gCLmNh9LhK89Qd6kQ6XNiw/Lx1FG7C/rZFrIw=,tag:+5vBr0oiqNOtoaoyRzjxtw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
