releases:
  - name: postgres-secret
    namespace: stipendiatet
    createNamespace: true
    chart: ./postgres/secrets
    version: "0.0.1"
    secrets:
      - ./postgres/secrets/secrets.yaml


  - name: postgres
    namespace: stipendiatet
    chart: oci://registry-1.docker.io/bitnamicharts/postgresql
    createNamespace: true
    version: "18.1.13"
    values:
      - ./postgres/values.yaml
    needs:
      - postgres-secret

  - name: backend
    chart: ./charts/stipendiatet/backend
    namespace: stipendiatet
    createNamespace: true
    values:
      - ./charts/stipendiatet/backend/values.yaml
    secrets:
      - ./charts/stipendiatet/backend/secrets.yaml

  - name: frontend
    chart: ./charts/stipendiatet/frontend
    namespace: stipendiatet
    createNamespace: true
    values:
      - ./charts/stipendiatet/frontend/values.yaml
    secrets:
      - ./charts/stipendiatet/frontend/secrets.yaml

  - name: admin-frontend
    chart: ./charts/stipendiatet/admin-frontend
    namespace: stipendiatet
    createNamespace: true
    values:
      - ./charts/stipendiatet/admin-frontend/values.yaml
    #secrets:
    #  - ./charts/stipendiatet/admin-frontend/secrets.yaml