service:
  port: 80

resources:

env:
  viteBackendUrl: "http://backend.stipendiatet.svc.cluster.local:8000/api"

ingress:
  host: stipendieadmin.labb.site

image:
  repository: seppaleinen/stipendariet-admin
  tag: latest
