"""
Admin categorization endpoints for foundation category management
"""

import logging
import uuid
from concurrent.futures import ThreadPoolExecutor

from fastapi import HTTPException, status

logger = logging.getLogger(__name__)


def reset_categories_endpoint():
    """
    Endpoint to reset all foundation categories to empty.
    After reset, categories will be regenerated by the scheduled categorization job,
    or can be triggered separately via a categorization endpoint.
    """
    try:
        logger.info("Admin triggered category reset")

        from app.foundation.categorization.categorize_foundations import FoundationCategorizer
        categorizer = FoundationCategorizer()

        # Reset all categories in the database (simple UPDATE, no heavy processing)
        reset_count = categorizer.reset_categories_in_db()

        # NOTE: Removed automatic recategorization - it was causing OOM kills
        # Categories will be regenerated by the scheduled job or manual trigger

        return {
            "status": "success",
            "message": f"Categories reset for {reset_count} foundations. Use 'Trigger Categorization' to recategorize.",
            "foundations_reset": reset_count
        }
    except Exception as e:
        logger.error(f"Error in admin category reset: {str(e)}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Category reset failed: {str(e)}"
        )


def trigger_bulk_categorization_endpoint():
    """
    Endpoint to trigger bulk foundation categorization as a background task.
    Returns a task_id that can be used to poll for progress.
    """
    try:
        logger.info("Admin triggered bulk foundation categorization")

        # Generate a unique task ID
        task_id = str(uuid.uuid4())

        # Create a task record in the task manager
        from app.foundation.task_manager import create_task
        create_task(task_id, task_name="bulk_categorization")

        def run_background_categorization():
            try:
                from app.foundation.categorization.categorize_foundations import FoundationCategorizer
                categorizer = FoundationCategorizer()
                categorizer.categorize_foundations_in_db(task_id=task_id)
            except Exception as e:
                logger.error(f"Background categorization task {task_id} failed: {e}")
                from app.foundation.task_manager import get_task
                task = get_task(task_id)
                if task:
                    task.set_error(str(e))

        # Run the background task in a separate thread
        executor = ThreadPoolExecutor(max_workers=1)
        executor.submit(run_background_categorization)
        # Don't wait for the executor to finish

        return {
            "status": "started",
            "message": "Bulk foundation categorization started",
            "task_id": task_id
        }
    except Exception as e:
        logger.error(f"Error starting bulk categorization: {str(e)}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to start bulk categorization: {str(e)}"
        )
